# Site
about_title: About me
projects_title: Personal projects
experience_title: Experience
awards_title: Awards
education_title: Education and Languages
more_title: A little more about me
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Gonzalo Chumillas
title: Web senior developer
email: gonzalo.chumillas@gmail.com
website: gonzalo-chumillas.github.io
github: github.com/gchumillas
linkedin: linkedin.com/in/gchumillas
phone: (+34) 611 079 599
location: Ciudad Real, Spain

# Social links
github_username: gchumillas
linkedin_username: gonzalo-chumillas-5303b5163

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi! my name's Gonzalo and I worked for over ten years building websites and web applications, mainly in PHP, MySQL, jQuery and later in Angular and React. I have also offered technical support, such as the administration of Linux-based servers. I consider myself specially qualified for the <mark>analysis</mark>, <mark>development</mark> and <mark>design</mark> of applications and user interfaces.

  **It's important for me to note that I'm currently looking for remote jobs.**

  I already worked remotely for quite some years with very good results.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# education_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Not everything is coding. I also like photography and exploring and capturing moments with my Ricoh GR II. Previously I had a Fuji X-T1, a fantastic camera, but it was a bit big for street photography.

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
