# Site
about_title: Sobre mí
projects_title: Proyectos personales
experience_title: Experiencia
awards_title: Reconocimientos
education_title: Educación
more_title: Un poco más sobre mí
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Gonzalo Chumillas
title: Desarrollador web senior
email: gonzalo.chumillas@gmail.com
website: github.com/gchumillas

# Social links
github_username: gchumillas
linkedin_username: gonzalo-chumillas-5303b5163

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hola, mi nombre es Gonzalo y soy desarrollador web senior. A lo largo de mi trayectoria profesional he desarrollado tanto aplicaciones como sitios web, aunque también he ofrecido soporte técnico, como la administración de servidores basados en Linux. Me considero especialmente habilidoso para el <mark>Análisis</mark>, <mark>Desarrollo</mark> y <mark>Maquetación</mark> de aplicaciones y sitios web.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# education_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  No todo va a ser programar. También me gusta la fotografía y salir con mi Ricoh GR II a cazar momentos. Antes tenía una Fuji X-T1, una excelente cámara, pero algo voluminosa para practicar la fotografía callejera. Aquí podréis ver algunas de mis fotos (ojo, no soy profesional):

  <a href="http://500px.com/gonzalochumillas" target="_blank">
    500px.com/gonzalochumillas
  </a>

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
